name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Get swift version
        run: swift --version # Swift 5.3.3
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      - name: Build and Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: xcodebuild test -scheme USAPopulationTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -sdk iphonesimulator



  
